### ISSUE TITLE
Laravel 5.4 Not Working v2.7.*

### ISSUE THREAD

**Issue by ahmeti** [Laravelium/laravel-sitemap#142]
Hello,
The latest version is not installing for Laravel 5.4

### Composer Error
```code
roumen/sitemap v2.7.2 requires illuminate/support 5.5.* -> satisfiable by illuminate/support[v5.5.0, v5.5.2].
```
Please add description to readme file

### For Laravel 5.4
```json
"roumen/sitemap": "2.6.*"
```

Thank you.

**Comment by Bhumibhalala** [comment]
Have got same issue.. Solved with "roumen/sitemap": "2.6.*" :)
