### ISSUE TITLE
Work without facades

### ISSUE THREAD

**Issue by devanes** [Laravelium/laravel-sitemap#144]
You have a manual how to use your package with Lumen. However this still requires Facades to be enabled. I use Lumen for performance reasons, so enabling Facades is something I try to avoid. Yours would be the only package I would need this for. It would be an improvement if you didn't use Facades in your own code. By using for example the app() and config() helpers you could avoid the use of Facades.

I'll have to work around this or just create the sitemap using my own code for now, because for me enabling Facades just won't do.

I'm using 2.6 by the way.

**Comment by solamichealolawale** [comment]
How does this work with lumen? 
I tried running this command and I get an error
![image](https://user-images.githubusercontent.com/12444227/119218929-9592e100-bada-11eb-9551-ed79dc6cf302.png)

**Comment by devanes** [comment]
@solamichealolawale You're replying to an old unrelated issue. You should probably start a new one.
