### ISSUE TITLE
Array required for the class constructor

### ISSUE THREAD

**Issue by MrTomAsh** [Laravelium/laravel-sitemap#153]
Hi,

this line:

`$sitemap = App::make("sitemap");`

starts giving me that error:

> Type error: Argument 1 passed to Roumen\Sitemap\Sitemap::__construct() must be of the type array, null given, called in /home/.../vendor/roumen/sitemap/src/Roumen/Sitemap/SitemapServiceProvider.php on line 52

I've tried adding an empty array but that doesn't help.

Can you please advice?

I'm using Laravel 5.5.32 and latest version of the plugin

Many thanks,
Tomasz

**Comment by MrTomAsh** [comment]
Ok, I've reached the bottom of the issue.

As the:
- font awesome 
- jquery
- bors-session-php
requires installing a balancer framework, and this one somehow overwriting laravel 'config' function here:
Line 216, /vendor/balancer/bors-core/inc/funcs.php
`if(!function_exists('config'))
{
	function config($key, $def = NULL) { return \B2\Cfg::get($key, $def); }
}`

and from now on the 'config' function starts returning null instead of laravel configuration. And the 'config' function is called here:
Line 50, /vendor/roumen/sitemap/src/Roumen/Sitemap/SitemapServiceProvider.php
`$config = config('sitemap');`
and returning null

Quick fix, but far away from a good solution is simply to change this line to:
`$config = \Config::get('sitemap');`

I don't know why this config function is taking over the laravel one but it does. I'll look for a better solution but I'll recommend amending this line of code and avoid that issue in the future.

Many thanks!

**Comment by shinnlu** [comment]
i have the same issue in laravel 6 production, but working in development environment.
both in the same machine.
in the production site, i use composer install --no-dev.
here is my packages list:

>     "require": {
>         "php": ">7.1.3",
>         "alexusmai/laravel-file-manager": "^2.4",
>         "babenkoivan/scout-elasticsearch-driver": "^4.0",
>         "baum/baum": "2.x-dev",
>         "fideloper/proxy": "^4.0",
>         "guzzlehttp/guzzle": "^6.3",
>         "intervention/image": "^2.3",
>         "laravel/framework": "^6.0",
>         "laravel/tinker": "^2.0",
>         "laravelcollective/html": "^6.0",
>         "laravelium/sitemap": "^6.0",
>         "maatwebsite/excel": "~3.1",
>         "mews/captcha": "~3.0.1",
>         "paypal/paypal-checkout-sdk": "1.0.1",
>         "paypal/rest-api-sdk-php": "*",
>         "steelywing/chinese": "^0.5.3",
>         "stripe/stripe-php": "^7.7"
>     },
>     "require-dev": {
>         "barryvdh/laravel-debugbar": "^3.2",
>         "composer/composer": "^1.9",
>         "filp/whoops": "^2.0",
>         "fzaninotto/faker": "^1.4",
>         "laravel/dusk": "^5.9",
>         "mockery/mockery": "^1.0",
>         "nunomaduro/collision": "^2.0",
>         "phpunit/phpunit": "^7.0",
>         "symfony/css-selector": "3.1.*",
>         "symfony/dom-crawler": "3.1.*",
>         "symfony/thanks": "^1.0"
>     },
