### ISSUE TITLE
Laravel 5.6 

### ISSUE THREAD

**Issue by KennedyTedesco** [Laravelium/laravel-sitemap#155]
Any plans to support Laravel 5.6? Thanks in advance.

**Comment by RoumenDamianoff** [comment]
Hi, @KennedyTedesco 

Version [2.8.1](https://github.com/Laravelium/laravel-sitemap/releases/tag/v2.8.1) is compatible with Laravel 5.6

**Comment by KennedyTedesco** [comment]
That’s awesome! Thank you.
