### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by gemal** [Laravelium/laravel-sitemap#158]
Is there support for Laravel 5.6 in the works :) ?

**Comment by erunion** [comment]
This library is installable, and functions, under 5.6 already.

**Comment by gemal** [comment]
Super. Sorry

**Comment by erunion** [comment]
@gemal Sorry, I didn't mean to come off as a dick there.

**Comment by gemal** [comment]
No problem. I'm just happy it works on 5.6 :)
