### ISSUE TITLE
is here a guide for the "styles_location" item?

### ISSUE THREAD

**Issue by bestony** [Laravelium/laravel-sitemap#159]
I read the test ,but here is not test for "styles_location"

can anyone give a guide or sample code to use "styles_location"

or how can i custom my sitemap?

**Comment by cubitworx** [comment]
@bestony  Don't know if you ever found a solution but looking at the source I found that the default location was set to `/vendor/sitemap/styles/`. So you simply need to change that but it must start & end with slashes.

**Comment by bestony** [comment]
@cubitworx I don't think this is a good solution. I control my code by git and CI & CD ,i always install my vendor by composer on server .

**Comment by cubitworx** [comment]
You should be committing your config/* folder to source control so this is the best option to save it to source control. Doing composer install on the server should not affect this config file if you have configured it correctly
