### ISSUE TITLE
Add Laravel 5.7 support

### ISSUE THREAD

**Issue by sangnguyenplus** [Laravelium/laravel-sitemap#163]
Laravel 5.7 is released yesterday so it's good if you can update this package to support Laravel 5.7

Thanks for a great package!

**Comment by Damianoff** [comment]
Hi,

Laravel 5.7 is already supported here - https://gitlab.com/Laravelium/Sitemap

**Comment by sangnguyenplus** [comment]
So I need to wait for releasing it on Github?

**Comment by Damianoff** [comment]
No, you can use `laravelium/sitemap` instead of `roumen/sitemap` now and don't care where is a package actually hosted. GitLab/GitHub/BitBucket is for development, [Packagist](https://packagist.org/packages/laravelium/sitemap) is for releasing composer packages.
