### ISSUE TITLE
Memory leak store sitemap

### ISSUE THREAD

**Issue by javiercno** [Laravelium/laravel-sitemap#170]
I am generating a sitemap of 30 million records with memory problems due to

$this->view->make('sitemap::'.$format, ['items' => $this->model->getItems(), 'style' => $style])->render();

Solutions?

**Comment by halaei** [comment]
@javiercno  I have just encountered the same issue. Did you find the source of memory leak or a solution?
It seems `$sitemap->model->resetItems();` doesn't clean memory.
I will send another issue after finding what is going on.

**Comment by halaei** [comment]
It  is an issue with Ignition. A fix would be not to install ignition in production.

**Comment by AMoktar** [comment]
> It seems `$sitemap->model->resetItems();` doesn't clean memory.

that's right, $sitemap->model->resetItems(); do nothing

**Comment by javiercno** [comment]
> It is an issue with Ignition. A fix would be not to install ignition in production. The issue might be fixed in ignition in newer versions, which I am not using at the moment.

The solution is not to install ignition in production, laravel-sitemap not is the problem.
